#! /bin/sh

# Kill if is running

killall sxhkd dunst xfce4-power-manager polybar

# Autostart

sxhkd -c ~/.config/bspwm/sxhkdrc &
nitrogen --restore &
setxkbmap pt &
xfce4-power-manager &
dunst &
$HOME/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           3

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc rule -r *:*

bspc rule -a Galculator state=floating
bspc rule -a discord desktop='^8'
bspc rule -a spotify desktop='^9'

# Colors

$HOME/.config/bspwm/colorschemes/dracula.sh &

