#!/usr/bin/env bash

# Kill if is running

killall sxhkd dunst xfce4-power-manager polybar

# Dual monitor stuff (Used on laptop)

# external -> Use external monitor as primary
# laptop -> Use laptop monitor as primary
# STILL TO IMPLEMENT
export DUAL_MODE="laptop"
if [[ $(xrandr -q | grep "HDMI-2") == *\ connected* ]]; then
    $HOME/.config/bspwm/utils/dual-integrated.sh &
elif [[ $(xrandr -q | grep "HDMI-1-2") == *\ connected* ]]; then
    $HOME/.config/bspwm/utils/dual-nvidia.sh &
else
    # should have a script for this (dunno if it works)
    # bspc monitor "$BSPWM_EXTERNALMONITOR" --remove > /dev/null
    # xrandr --output "$BSPWM_EXTERNALMONITOR" --off
    # xrandr --auto

    unset DUAL_MODE

    xrandr --auto
    bspc config remove_disabled_monitors true
    bspc config remove_unplugged_monitors true

    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
    # if [ -f $HOME/.config/alacritty/alacritty.yml ]; then
    #     sed -i "s/size: .*$/size: 9.0/" $HOME/.config/alacritty/alacritty.yml
    # fi
fi

# Autostart

sxhkd -c ~/.config/bspwm/sxhkdrc &
nitrogen --restore &
# setxkbmap pt &
xfce4-power-manager &
dunst &
$HOME/.config/polybar/launch.sh &

bspc config border_width         2
bspc config window_gap           3

# Use alt for floating windows actions
bspc config pointer_modifier mod1

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc rule -r *:*

bspc rule -a Galculator state=floating
bspc rule -a matplotlib state=floating
bspc rule -a discord desktop='^8' follow=off
bspc rule -a spotify desktop='^9'

# Colors

$HOME/.config/bspwm/colorschemes/tokyonight.sh &

# Scratchpads
bspc rule -a scratchterm sticky=on state=floating rectangle=1000x600+475+250
