#! /bin/sh

# Kill if is running

killall sxhkd dunst xfce4-power-manager polybar

# Dual monitor stuff (Used on laptop)

if [ -f $HOME/.config/alacritty/alacritty.yml ]; then
    sed -i "s/size: .*$/size: 8.0/" $HOME/.config/alacritty/alacritty.yml
fi

unset DUAL_MODE
if [[ $(xrandr -q | grep "HDMI-2") == *\ connected* ]]; then
    # external -> Use external monitor as primary
    # laptop -> Use laptop monitor as primary
    # STILL TO IMPLEMENT

    export DUAL_MODE="external"
    $HOME/.config/bspwm/utils/dual.sh &
fi

# Autostart

sxhkd -c ~/.config/bspwm/sxhkdrc &
nitrogen --restore &
setxkbmap pt &
xfce4-power-manager &
dunst &
$HOME/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           3

# Use alt for floating windows actions
bspc config pointer_modifier mod1

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc rule -r *:*

bspc rule -a Galculator state=floating
bspc rule -a discord desktop='^8'
bspc rule -a spotify desktop='^9'

# Colors

$HOME/.config/bspwm/colorschemes/dracula.sh &

# Scratchpads
bspc rule -a scratchterm sticky=on state=floating rectangle=1000x600+475+250

